config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    resources :ideas, shallow: true
  end
  devise_for :users, :path => ''
  root                                'pages#home'
  get     'feature'         =>        'pages#feature'
  get     'leaderboard'     =>        'pages#leaderboard'
  get     'support/write'   =>        'pages#write'
  get     'support/howto'   =>        'pages#howto'
  get     'support/report'  =>        'pages#report'
  get     'support'         =>        'pages#support'
  get     'feedline'        =>        'topics#feedline'
  get     'my_idea'         =>        'ideas#my_idea'
  get     'my_topic'        =>        'topics#my_topic'
  get ':username', to: 'profiles#show', as: :profile
  get ':username/edit', to: 'profiles#edit', as: :edit_profile
  patch ':username/edit', to: 'profiles#update', as: :update_profile
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true
  belongs_to :topic
  belongs_to :user
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /myideas
  # GET /myideas.json
  def my_idea
    @ideas = current_user.ideas
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @topic = Topic.find(params[:topic_id])
    @idea = @topic.ideas.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @topic = Topic.find(params[:topic_id])
    @idea = @topic.ideas.new(idea_params)
    @idea.user_id = current_user.id
    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.js { render 'destroy_idea.js.erb' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:topic_id, :title, :body)
    end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_for([@idea.topic, @idea]) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, "Give Your Idea A Nice Title" %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body, "Explain Your Idea More" %><br>
    <%= f.text_area :body, rows: "16", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Publish Idea", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/ideas/destroy.js.erb
$('div#idea_<%= @idea.id %>').fadeOut();

app/views/ideas/destroy_idea.js.erb
$('div#idea_<%= @idea.id %>').fadeOut();

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ideas</h1>

<table>
  <thead>
    <tr>
      <th>Topic</th>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.topic %></td>
        <td><%= idea.title %></td>
        <td><%= idea.body %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/my_idea.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'layouts/sidebar' %>
  </div>

  <div class="col-md-7 col-md-offset-1">

    <div class="page-header">
      <h3 class="text-primary">My Idea</h3>
    </div>

    <div class="row">
      <div class="col-md-12">
        <% if @ideas.empty? %>
          <h5>Opps! You don't have any ideas posted yet.</h5>
        <% else %>
          <% @ideas.each do |idea| %>
            <div class="well">
              <div class="row">
                <div class="col-md-2">
                  <%= image_tag idea.user.avatar.url(:medium), class: 'img-circle' %>
                </div>
                <div class="col-md-10">
                  <h4>
                    <%= link_to idea.title, idea_path(idea) %>
                    <small class="pull-right middle">
                      <%= time_ago_in_words(idea.created_at) %> ago

                      <div class="dropdown pull-right">
                        <a class="dropdown-toggle topic-settings-inverse" data-toggle="dropdown">
                          <%= icon('circle-o fa-lg') %>
                        </a>
                        <ul class="dropdown-menu">
                          <li class="dropdown-header">More</li>
                          <li>
                            <%= link_to("#") do %>
                              <%= icon('share fa-fw') %>&nbsp;Share Idea
                            <% end %>
                          </li>
                          <% if idea.user_id == current_user.id %>
                          <li class="dropdown-header">Topic Settings</li>
                          <li>
                            <%= link_to(edit_idea_path(idea)) do %>
                              <%= icon('edit fa-fw') %>&nbsp;Edit Idea
                            <% end %>
                          </li>
                          <li>
                            <%= link_to(idea, method: :delete, data: { confirm: "Are You sure?" }, remote: true ) do %>
                              <%= icon('trash-o fa-fw') %>&nbsp;Delete Idea
                            <% end %>
                          </li>
                          <% end %>
                        </ul>
                      </div>
                    </small>
                  </h4>
                  <%= active_link_to "like" do %>
                    <%= icon('thumbs-o-up fa-fw') %>&nbsp;I like this idea
                  <% end %>
                  &nbsp;
                  <%= active_link_to "like" do %>
                    <%= icon('thumbs-o-down fa-fw') %>&nbsp;I disagree
                  <% end %>
                  &nbsp;
                  <%= active_link_to "comment" do %>
                    <%= icon('comment-o fa-fw') %>&nbsp;Comment
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/ideas/new.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'layouts/sidebar' %>
  </div>

  <div class="col-md-7 col-md-offset-1">
    <div class="page-header">
      <h3 class="text-primary">New Idea</h3>
    </div>
    
    <%= render 'form' %>
  </div>
</div>

app/views/ideas/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'layouts/sidebar' %>
  </div>

  <div class="col-md-7 col-md-offset-1">
    <h2><%= @idea.title %></h2>
    <small class="block padding-b-custom">
      Posted by <%= link_to @idea.user.username, profile_path(@idea.user.username)  %>
      &nbsp;|&nbsp;
      <%= time_ago_in_words(@idea.created_at) %> ago
    </small>
    <hr>
    <article>
      <%= markdown(@idea.body) %>
    </article>

    <div class="row">
      <div class="col-md-12">
        <div class="page-header">
          <h3 class="text-primary">List of Comments
            <%= active_link_to("#", class: "btn btn-primary pull-right") do %>
              <%= icon('comment-o fa-fw') %>&nbsp;New Comment
            <% end %>
          </h3>
        </div>
      </div>
    </div>
  </div>
</div>