config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    resources :ideas, shallow: true
  end
  devise_for :users, :path => ''
  root                                'pages#home'
  get     'feature'         =>        'pages#feature'
  get     'leaderboard'     =>        'pages#leaderboard'
  get     'support/write'   =>        'pages#write'
  get     'support/howto'   =>        'pages#howto'
  get     'support/report'  =>        'pages#report'
  get     'support'         =>        'pages#support'
  get     'feedline'        =>        'topics#feedline'
  get     'my_idea'         =>        'ideas#my_idea'
  get     'my_topic'        =>        'topics#my_topic'
  get ':username', to: 'profiles#show', as: :profile
  get ':username/edit', to: 'profiles#edit', as: :edit_profile
  patch ':username/edit', to: 'profiles#update', as: :update_profile
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true

  belongs_to :user
  has_many :ideas, dependent: :destroy

  def self.published
    where(is_draft: false).order('created_at DESC')
  end

  def self.unpublished
    where(is_draft: true).order('created_at DESC')
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :owned_topic, only: [:edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @published_topics = current_user.topics.published
    @unpublished_topics = current_user.topics.unpublished
  end

  # GET /mytopics
  # GET /mytopics.json
  def my_topic
    @published_topics = current_user.topics.published
    @unpublished_topics = current_user.topics.unpublished
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = current_user.topics.new
  end

  # GET /topics/1/edit
  def edit
  end

  def feedline
    @topics = Topic.published
  end

  # topic /topics
  # topic /topics.json
  def create
    @topic = current_user.topics.new(topic_params)
    if @topic.save
      redirect_to @topic, notice: params[:is_draft]? 'Topic successfully save as draft.': 'Topic successfully published.'
    else
      render 'new'
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
      unless params[:is_draft]
        @topic.is_draft = false
        if @topic.update(topic_params)
          redirect_to @topic, success: 'Topic successfully published.'
        else
          render 'edit'
        end
      else
        @topic.is_draft = true
        if @topic.update(topic_params)
          redirect_to @topic, notice: 'Topic save as draft.'
        else
          render 'edit'
        end
      end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to :back, success: 'Topic successfully deleted.' }
      format.js { render 'destroy_topic.js.erb' }
    end
  end

  private
    # Use callback to authorize topic
    def owned_topic
      unless current_user.id == @topic.user_id
        flash[:alert] = "Opps! You don't have permission to do that."
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:user_id, :title, :body, :is_draft, :is_open)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :title, "Give Your Topic A Nice Title" %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body, "Explain Your Topic More" %><br>
    <%= f.text_area :body, :class => "form-control", :rows => 16 %>
  </div>
  <div class="form-group">
    <%= f.submit "Save as Draft", name: 'is_draft', class: "btn btn-info" %>
    <%= f.submit "Publish", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/topics/_published.html.erb
<% if @published_topics.empty? %>
  <h5>Opps! There is no published topic yet.</h5>
<% else %>
  <% @published_topics.each do |topic| %>
  <div class="panel panel-primary topic" id="topic_<%= topic.id %>">
    <div class="panel-heading">
      <%= image_tag topic.user.avatar.url(:small), class: 'img-circle' %>
      &nbsp;<%= link_to topic.user.username, profile_path(topic.user.username), class: "topic-profile-link" %>
      <small class="pull-right middle">
        <%= time_ago_in_words(topic.created_at) %> ago

        <div class="dropdown pull-right">
          <a class="dropdown-toggle topic-settings" data-toggle="dropdown">
            <%= icon('circle-o fa-lg') %>
          </a>
          <ul class="dropdown-menu">
            <li class="dropdown-header">More</li>
            <li>
              <%= link_to("#") do %>
                <%= icon('share fa-fw') %>&nbsp;Share topic
              <% end %>
            </li>
            <% if topic.user.id == current_user.id %>
            <li class="dropdown-header">Topic Settings</li>
            <li>
              <%= link_to(edit_topic_path(topic)) do %>
                <%= icon('edit fa-fw') %>&nbsp;Edit topic
              <% end %>
            </li>
            <li>
              <%= link_to(topic, method: :delete, data: { confirm: "Are you sure?" }, remote: true ) do %>
                <%= icon('trash-o fa-fw') %>&nbsp;Delete topic
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>

      </small>

    </div>
    <div class="panel-body">
      <h4><%= link_to topic.title, topic_path(topic.id) %></h4>
      <div class="justify">
        <% if topic.body.length > 200 %>
          <%= truncate(topic.body, length: 200) %>
          <%= link_to 'Read more', topic_path(topic) %>
        <% else %>
          <%= topic.body %>
        <% end %>
      </div>
    </div>
    <div class="panel-footer">
      <%= link_to(new_topic_idea_path(topic), class: "campaign-icon") do %>
        <%= icon('lightbulb-o fa-lg') %> Share Your Idea
      <% end %>
    </div>
  </div>
  <% end %>

<% end %>

app/views/topics/_topics.html.erb
<% if @topics.empty? %>
  <h5>Opps! There is no topic yet.</h5>
<% else %>
  <% @topics.each do |topic| %>
  <div class="panel panel-primary topic" id="topic_<%= topic.id %>">
    <div class="panel-heading">
      <%= image_tag topic.user.avatar.url(:small), class: 'img-circle' %>
      &nbsp;<%= link_to topic.user.username, profile_path(topic.user.username), class: "topic-profile-link" %>
      <small class="pull-right middle">
        <%= time_ago_in_words(topic.created_at) %> ago

        <div class="dropdown pull-right">
          <a class="dropdown-toggle topic-settings" data-toggle="dropdown">
            <%= icon('circle-o fa-lg') %>
          </a>
          <ul class="dropdown-menu">
            <li class="dropdown-header">More</li>
            <li>
              <%= link_to("#") do %>
                <%= icon('share fa-fw') %>&nbsp;Share topic
              <% end %>
            </li>
            <% if topic.user.id == current_user.id %>
            <li class="dropdown-header">Topic Settings</li>
            <li>
              <%= link_to(edit_topic_path(topic)) do %>
                <%= icon('edit fa-fw') %>&nbsp;Edit topic
              <% end %>
            </li>
            <li>
              <%= link_to(topic, method: :delete, data: { confirm: "Are you sure?" }, remote: true ) do %>
                <%= icon('trash-o fa-fw') %>&nbsp;Delete topic
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>

      </small>

    </div>
    <div class="panel-body">
      <h4><%= link_to topic.title, topic_path(topic.id) %></h4>
      <div class="justify">
        <% if topic.body.length > 200 %>
          <%= truncate(topic.body, length: 200) %>
          <%= link_to 'Read more', topic_path(topic) %>
        <% else %>
          <%= topic.body %>
        <% end %>
      </div>
    </div>
    <div class="panel-footer">
      <%= link_to(new_topic_idea_path(topic), class: "campaign-icon") do %>
        <%= icon('lightbulb-o fa-lg') %> Share Your Idea
      <% end %>
    </div>
  </div>
  <% end %>

<% end %>

app/views/topics/_unpublished.html.erb
<% @unpublished_topics.each do |topic| %>
<div class="panel panel-primary topic" id="topic_<%= topic.id %>">
  <div class="panel-heading">
    <%= image_tag topic.user.avatar.url(:small), class: 'img-circle' %>
    &nbsp;<%= link_to topic.user.username, profile_path(topic.user.username), class: "topic-profile-link" %>
    <small class="pull-right middle">
      <%= time_ago_in_words(topic.created_at) %> ago

      <div class="dropdown pull-right">
        <a class="dropdown-toggle topic-settings" data-toggle="dropdown">
          <%= icon('circle-o fa-lg') %>
        </a>
        <ul class="dropdown-menu">
          <li class="dropdown-header">More</li>
          <li>
            <%= link_to("#") do %>
              <%= icon('share fa-fw') %>&nbsp;Share topic
            <% end %>
          </li>
          <% if topic.user.id == current_user.id %>
          <li class="dropdown-header">Topic Settings</li>
          <li>
            <%= link_to(edit_topic_path(topic)) do %>
              <%= icon('edit fa-fw') %>&nbsp;Edit topic
            <% end %>
          </li>
          <li>
            <%= link_to(topic, method: :delete, data: { confirm: "Are you sure?" }, remote: true ) do %>
              <%= icon('trash-o fa-fw') %>&nbsp;Delete topic
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>

    </small>

  </div>
  <div class="panel-body">
    <h4><%= link_to topic.title, topic_path(topic.id) %></h4>
    <div class="justify">
      <% if topic.body.length > 200 %>
        <%= truncate(topic.body, length: 200) %>
        <%= link_to 'Read more', topic_path(topic) %>
      <% else %>
        <%= topic.body %>
      <% end %>
    </div>
  </div>
  <div class="panel-footer">
    <%= link_to(new_topic_idea_path(topic), class: "campaign-icon") do %>
      <%= icon('lightbulb-o fa-lg') %> Share Your Idea
    <% end %>
  </div>
</div>
<% end %>

app/views/topics/destroy_topic.js.erb
$('div#topic_<%= @topic.id %>').fadeOut();

app/views/topics/edit.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'layouts/sidebar' %>
  </div>

  <div class="col-md-7 col-md-offset-1">
    <div class="page-header">
      <h3>Edit Topic</h3>
    </div>

    <%= render 'form' %>
  </div>
</div>

app/views/topics/feedline.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'layouts/sidebar' %>
  </div>

  <div class="col-md-7 col-md-offset-1">
    <div class="page-header">
      <h3 class="text-primary">Feedline
        <%= active_link_to(new_topic_path, :active => :exact, class: "btn btn-primary pull-right") do %>
          <%= icon('pencil fa-fw') %>&nbsp;New Topic
        <% end %>
      </h3>

    </div>
    <%= render 'topics/topics' %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'layouts/sidebar' %>
  </div>

  <div class="col-md-7 col-md-offset-1">

    <div class="page-header">
      <h3 class="text-primary">My Topic</h3>
    </div>

    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active">
        <a href="#published" aria-controls="published" role="tab" data-toggle="tab">Published</a>
      </li>
      <li role="presentation">
        <a href="#draft" aria-controls="draft" role="tab" data-toggle="tab">Draft</a>
      </li>
    </ul>

    <div class="tab-content">
      <div role="tabpanel" class="tab-pane padding-v active" id="published">
        <%= render 'topics/published' %>
      </div>
      <div role="tabpanel" class="tab-pane padding-v" id="draft">
        <%= render 'topics/unpublished' %>
      </div>
    </div>

  </div>
</div>

app/views/topics/my_topic.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'layouts/sidebar' %>
  </div>

  <div class="col-md-7 col-md-offset-1">

    <div class="page-header">
      <h3 class="text-primary">My Topic</h3>
    </div>

    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active">
        <a href="#published" aria-controls="published" role="tab" data-toggle="tab">Published</a>
      </li>
      <li role="presentation">
        <a href="#draft" aria-controls="draft" role="tab" data-toggle="tab">Draft</a>
      </li>
    </ul>

    <div class="tab-content">
      <div role="tabpanel" class="tab-pane padding-v active" id="published">
        <%= render 'topics/published' %>
      </div>
      <div role="tabpanel" class="tab-pane padding-v" id="draft">
        <%= render 'topics/unpublished' %>
      </div>
    </div>

  </div>
</div>

app/views/topics/new.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'layouts/sidebar' %>
  </div>

  <div class="col-md-7 col-md-offset-1">
    <div class="page-header">
      <h3 class="text-primary">New Topic</h3>
    </div>

    <%= render 'form' %>
  </div>

</div>

app/views/topics/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'layouts/sidebar' %>
  </div>

  <div class="col-md-7 col-md-offset-1">
    <h2><%= @topic.title %></h2>
    <small class="block padding-b-custom">
      Posted by <%= link_to @topic.user.username, profile_path(@topic.user.username)  %>
      &nbsp;|&nbsp;
      <%= time_ago_in_words(@topic.created_at) %> ago
    </small>
    <hr>
    <article>
      <%= markdown(@topic.body) %>
    </article>


    <div class="row">
      <div class="col-md-12">
        <div class="page-header">
          <h3 class="text-primary">List of Ideas
            <%= active_link_to(new_topic_idea_path(@topic.id), :active => :exact, class: "btn btn-primary pull-right") do %>
              <%= icon('lightbulb-o fa-fw') %>&nbsp;New Idea
            <% end %>
          </h3>
        </div>
        <% if @topic.ideas.empty? %>
          <h5>Opps! There is no idea posted for this topic yet.</h5>
        <% else %>
          <% @topic.ideas.order('created_at DESC').each do |idea| %>
          <div class="well" id="idea_<%= idea.id %>">
            <div class="row">
              <div class="col-md-2">
                <%= image_tag idea.user.avatar.url(:medium), class: 'img-circle' %>
              </div>
              <div class="col-md-10">
                <h4>
                  <%= link_to idea.title, idea_path(idea) %>
                  <small class="pull-right middle">
                    <%= time_ago_in_words(idea.created_at) %> ago

                    <div class="dropdown pull-right">
                      <a class="dropdown-toggle topic-settings-inverse" data-toggle="dropdown">
                        <%= icon('circle-o fa-lg') %>
                      </a>
                      <ul class="dropdown-menu">
                        <li class="dropdown-header">More</li>
                        <li>
                          <%= link_to("#") do %>
                            <%= icon('share fa-fw') %>&nbsp;Share Idea
                          <% end %>
                        </li>
                        <% if idea.user_id == current_user.id %>
                        <li class="dropdown-header">Topic Settings</li>
                        <li>
                          <%= link_to(edit_idea_path(idea)) do %>
                            <%= icon('edit fa-fw') %>&nbsp;Edit Idea
                          <% end %>
                        </li>
                        <li>
                          <%= link_to(idea, method: :delete, data: { confirm: "Are You sure?" }, remote: true ) do %>
                            <%= icon('trash-o fa-fw') %>&nbsp;Delete Idea
                          <% end %>
                        </li>
                        <% end %>
                      </ul>
                    </div>
                  </small>
                </h4>
                <%= active_link_to "like" do %>
                  <%= icon('thumbs-o-up fa-fw') %>&nbsp;I like this idea
                <% end %>
                &nbsp;
                <%= active_link_to "like" do %>
                  <%= icon('thumbs-o-down fa-fw') %>&nbsp;I disagree
                <% end %>
                &nbsp;
                <%= active_link_to "comment" do %>
                  <%= icon('comment-o fa-fw') %>&nbsp;Comment
                <% end %>
              </div>
            </div>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

</div>