config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    resources :ideas, shallow: true
  end
  devise_for :users, :path => ''
  root                                'pages#home'
  get     'feature'         =>        'pages#feature'
  get     'leaderboard'     =>        'pages#leaderboard'
  get     'support/write'   =>        'pages#write'
  get     'support/howto'   =>        'pages#howto'
  get     'support/report'  =>        'pages#report'
  get     'support'         =>        'pages#support'
  get     'feedline'        =>        'topics#feedline'
  get     'my_idea'         =>        'ideas#my_idea'
  get     'my_topic'        =>        'topics#my_topic'
  get ':username', to: 'profiles#show', as: :profile
  get ':username/edit', to: 'profiles#edit', as: :edit_profile
  patch ':username/edit', to: 'profiles#update', as: :update_profile
end

app/views/pages/_sidebar.html.erb
<div class="list-group">
  <%= active_link_to "Support", support_path, :active => :exclusive, class: "list-group-item" %>
  <%= active_link_to "How to use Aidia", support_howto_path, :active => :exclusive, class: "list-group-item" %>
  <%= active_link_to "Writing on Aidia", support_write_path, class: "list-group-item" %>
  <%= active_link_to "Report Issue", support_report_path, class: "list-group-item" %>
</div>

app/views/pages/feature.html.erb
You can use simple features to format your wrting on Aidia.

app/views/pages/home.html.erb
<div class="jumbotron center padding-v">
  <h1 class="headline">Aidia</h1>
  <p class="lead"></p>
  <br>
  <%= link_to "Sign Up For Free", new_user_registration_path, class: "btn btn-primary uppercase bold outline" %>
</div>

app/views/pages/howto.html.erb
<div class="row">
  <div class="col-md-3 padding-v-custom">
    <%= render 'sidebar' %>
  </div>

  <div class="col-md-7 col-md-offset-1">
    <div class="page-header">
      <h1 class="text-primary">How to use Aidia</h1>
    </div>
    <p>
      Step-by-step guides on how to use Aidia.
    </p>
    <div class="padding-v">
      <h3 class="text-primary">1. Open Topic</h3>
      <p>
        You can assume topic is just like a category. Give it a nice title. If you want to describe more, writing a rules or anything, you can just write on the next input.
      </p>
      <%= image_tag('help/step1.png', class: "img-responsive") %>
    </div>

    <div class="padding-v">
      <h3 class="text-primary">2. Get feedback from another users.</h3>
      <p>
        Any Users on Aidia can contibute an idea to the published topic.
      </p>
      <%= image_tag('help/step2.png', class: "img-responsive") %>
    </div>

    <div class="padding-v">
      <h3 class="text-primary">3. Idea can be voted and discuss more.</h3>
      <p>
        Just like Facebook's post or Twitter's tweet, idea can be voted by Likes and can be discussed by send a comment.
      </p>
      <%= image_tag('help/step3.png', class: "img-responsive") %>
    </div>
  </div>
</div>

app/views/pages/leaderboard.html.erb
<h1>Pages#leaderboard</h1>
<p>Find me in app/views/pages/leaderboard.html.erb</p>

app/views/pages/report.html.erb
<div class="row">
  <div class="col-md-3 padding-v-custom">
    <%= render 'sidebar' %>
  </div>

  <div class="col-md-7 col-md-offset-1">
    <div class="page-header">
      <h1 class="text-primary">Report Issue</h1>
    </div>

  </div>
</div>

app/views/pages/support.html.erb
<div class="row">
  <div class="col-md-3 padding-v-custom">
    <%= render 'sidebar' %>
  </div>

  <div class="col-md-7 col-md-offset-1">
    <div class="page-header">
      <h1 class="text-primary">Support&nbsp;<small>sometimes you just need a little help</small></h1>
    </div>
    <div class="padding-v">
      <ul class="nav nav-pills nav-stacked">
        <li>
          <%= active_link_to(support_howto_path) do %>
            <%= icon('bars fa-fw') %>&nbsp;How to use Aidia
          <% end %>
        </li>
        <li>
          <%= active_link_to(support_write_path) do %>
            <%= icon('bars fa-fw') %>&nbsp;Writing on Aidia
          <% end %>
        </li>
        <li>
          <%= active_link_to(support_report_path) do %>
            <%= icon('bars fa-fw') %>&nbsp;Report Issue
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/pages/write.html.erb
<div class="row">
  <div class="col-md-3 padding-v-custom">
    <%= render 'sidebar' %>
  </div>

  <div class="col-md-7 col-md-offset-1">
    <div class="page-header">
      <h1 class="text-primary">Writing on Aidia</h1>
    </div>
    <p>
       Create sophisticated formatting for your writings on Aidia with simple syntax. Aidia support Markdown Syntax for better writing.
    </p>
    <p>
      <ul>
        <li><a href="#heading">Heading</a></li>
        <li><a href="#stylingtext">Styling Text</a></li>
        <li><a href="#quotingtext">Quoting Text</a></li>
        <li><a href="#quotingcode">Quoting Code</a></li>
        <li><a href="#links">Links</a></li>
        <li><a href="#lists">Lists</a></li>
      </ul>
    </p>

    <h2 class="text-primary" id="heading">Heading</h2>
    <hr>
    <p>
      To create a heading, you can add one to six <mark>#</mark> symbols before your heading text. The number of <mark>#</mark> you use will determine the size of the heading.
    </p>
    <h3>Example</h3>
    <hr>
    <pre>
      # Heading 1 <br>
      ## Heading 2 <br>
      ### Heading 3 <br>
      #### Heading 4 <br>
      ##### Heading 5 <br>
      ###### Heading 6 <br>
    </pre>
    <h3>Preview</h3>
    <hr>
    <p>
      <h1>Heading 1</h1>
      <h2>Heading 2</h2>
      <h3>Heading 3</h3>
      <h4>Heading 4</h4>
      <h5>Heading 5</h5>
      <h6>Heading 6</h6>
    </p>
  </div>
</div>