config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    resources :ideas, shallow: true
  end
  devise_for :users, :path => ''
  root                                'pages#home'
  get     'feature'         =>        'pages#feature'
  get     'leaderboard'     =>        'pages#leaderboard'
  get     'support/write'   =>        'pages#write'
  get     'support/howto'   =>        'pages#howto'
  get     'support/report'  =>        'pages#report'
  get     'support'         =>        'pages#support'
  get     'feedline'        =>        'topics#feedline'
  get     'my_idea'         =>        'ideas#my_idea'
  get     'my_topic'        =>        'topics#my_topic'
  get ':username', to: 'profiles#show', as: :profile
  get ':username/edit', to: 'profiles#edit', as: :edit_profile
  patch ':username/edit', to: 'profiles#update', as: :update_profile
end

app/views/layouts/_canvas.html.erb
<canvas></canvas>

<script type="text/javascript">

      document.addEventListener('onclick', function (e) {
          e.preventDefault()
      })
      var c = document.getElementsByTagName('canvas')[0],
          x = c.getContext('2d'),
          pr = window.devicePixelRatio || 1,
          w = window.innerWidth,
          h = window.innerHeight,
          f = 90,
          q,
          m = Math,
          r = 0,
          u = m.PI*2,
          v = m.cos,
          z = m.random
      c.width = w*pr
      c.height = h*pr
      x.scale(pr, pr)
      x.globalAlpha = 0.6
      function i(){
          x.clearRect(0,0,w,h)
          q=[{x:0,y:h*.7+f},{x:0,y:h*.7-f}]
          while(q[1].x<w+f) d(q[0], q[1])
      }
      function d(i,j){
          x.beginPath()
          x.moveTo(i.x, i.y)
          x.lineTo(j.x, j.y)
          var k = j.x + (z()*2-0.25)*f,
              n = y(j.y)
          x.lineTo(k, n)
          x.closePath()
          r-=u/-50
          x.fillStyle = '#'+(v(r)*127+128<<16 | v(r+u/3)*127+128<<8 | v(r+u/3*2)*127+128).toString(16)
          x.fill()
          q[0] = q[1]
          q[1] = {x:k,y:n}
      }
      function y(p){
          var t = p + (z()*2-1.1)*f
          return (t>h||t<0) ? y(p) : t
      }
      document.onclick = i
      document.ontouchstart = i
      i()
</script>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: [:alert, alert_for(name), "center" "alert-dismissible"] %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <strong><%= link_to "Aidia", root_path %></strong>&nbsp;|&nbsp;<small><%= Time.now.year %>&nbsp;&nbsp;Made with <i class="fa fa-heart"></i> by Khai Rahman</small>
      </div>

      <div class="col-md-4 col-md-offset-4">
        <nav class="pull-right">
          <%= link_to "Feature", feature_path %>
          <%= link_to "Leaderboard", leaderboard_path %>
          <%= link_to "Support", support_path, target: "_blank" %>
        </nav>
      </div>

    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
        <%= link_to "Aidia", feedline_path, class: "navbar-brand" %>
      <% else %>
        <%= link_to "Aidia", root_path, class: "navbar-brand" %>
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="app-navbar-collapse">

      <% if user_signed_in? %>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search Aidia">
            <button class='btn btn-link search-btn'>
              <%= icon('search') %>
            </button>
          </div>
        </form>
      <% end %>

      <% unless user_signed_in? %>
        <ul class="nav navbar-nav">
          <li><%= link_to "Feature", feature_path %></li>
          <li><%= link_to "Feedline", "#" %></li>
          <li><%= link_to "Leaderboard", leaderboard_path %></li>
        </ul>
      <% end %>


      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                  <%= current_user.username %> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li class="dropdown-header">Profile Settings</li>
                <li>
                  <%= active_link_to(edit_profile_path(current_user.username)) do %>
                    <%= icon('user fa-fw') %>&nbsp;Edit Profile
                  <% end %>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <%= active_link_to(support_path, target: "_blank") do %>
                    <%= icon('exclamation fa-fw') %>&nbsp;Support
                  <% end %>
                </li>
                <li>
                  <%= active_link_to(destroy_user_session_path, :method => 'delete') do %>
                    <%= icon('sign-out fa-fw') %>&nbsp;Sign out
                  <% end %>
                </li>
              </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<h4 class="inline-block padding-h">
  <%= image_tag current_user.avatar.url(:medium), class: 'img-circle' %>
  &nbsp;
  <%= active_link_to(profile_path(current_user.username)) do %>
    <%= current_user.username %>
  <% end %>
</h4>

<div class="list-group sidebar-padding-top">

  <%= active_link_to(feedline_path, class: "list-group-item") do %>
    <%= icon('bars fa-fw') %>&nbsp;Feedline
  <% end %>
  <%= active_link_to(new_topic_path, :active => :exact, class: "list-group-item") do %>
    <%= icon('pencil fa-fw') %>&nbsp;New Topic
  <% end %>
  <%= active_link_to(my_topic_path, class: "list-group-item") do %>
    <%= icon('edit fa-fw') %>&nbsp;My Topic
  <% end %>
  <%= active_link_to(my_idea_path, class: "list-group-item") do %>
    <%= icon('lightbulb-o fa-fw') %>&nbsp;My Idea
  <% end %>

</div>

<div class="list-group">
  <%= active_link_to("ha", class: "list-group-item") do %>
    <%= icon('trophy fa-fw') %>&nbsp;Leaderboard
  <% end %>
  <%= active_link_to("ha", class: "list-group-item") do %>
    <%= icon('flag fa-fw') %>&nbsp;Idea In Action
  <% end %>
  <%= active_link_to("ha", class: "list-group-item") do %>
    <%= icon('flag-checkered  fa-fw') %>&nbsp;Top All Time
  <% end %>
</div>

<div class="list-group">
  <%= active_link_to(support_path, class: "list-group-item", target: "_blank") do %>
    <%= icon('exclamation fa-fw') %>&nbsp;Support
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aidia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
<body>
  <div class="pace pace-inactive">
    <div class="pace-progress" data-progress-text="100%" data-progress="99" style="transform: translate3d(100%, 0px, 0px);"></div>
    <div class="pace-progress-inner"></div>
  </div>
  <%= render 'layouts/nav' %>

  <div class="container animated fadeIn" id="mycontainer">
    <%= render 'layouts/flash' %>
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= render "layouts/canvas" if current_page?(root_path) %>

</body>
</html>